### ISSUE TITLE
How to call undocumented Plotly calls

### ISSUE THREAD

**Issue by sjennen** [David-Desmaisons/vue-plotly#3]
Is there a way to call Plotly.Fx.hover using this wrapper?  We have a a need for that functionality based on the code from this page: https://plot.ly/javascript/hover-events/#triggering-hover-events

**Comment by Codermar** [comment]
The plotly instance could be passed back to the component via an event and then you could use anything in it. I can do a quick PR for this if still interested.

```javascript 
 // Plotly.vue
  mounted() {
    Plotly.newPlot(this.$el, this.data, this.innerLayout, this.options);
    events.forEach(evt => {
      this.$el.on(evt.completeName, evt.handler(this));
    });
    this.$emit("plotlyready", Plotly);
  }, 
```

**Comment by David-Desmaisons** [comment]
@sjennen You can import ploty in your code to access  Plotly.Fx.hover.

**Comment by tuomassa** [comment]
@David-Desmaisons could you give an example? I don't find anything related to Fx in plotly when imported.

**Comment by bennybobw** [comment]
It's been a while since anyone commented on this, but here's what I did:

````javascript
import { Plotly } from 'vue-plotly'
import * as PlotlyJs from 'plotly.js'
// then
PlotlyJs.Fx.hover()
````
