### ISSUE TITLE
Hide Plotly Logo

### ISSUE THREAD

**Issue by Kyxsune** [David-Desmaisons/vue-plotly#4]
Hey,

Thanks a ton for the amazing wrapper, has made my first time using vue (and plotly) an enjoyable experience. I was wondering how to hide the plotly logo in the modebar using these [instructions](https://plot.ly/javascript/configuration-options/#hide-the-plotly-logo-on-the-modebar) from within your wrapper. Any help is welcomed,

Thanks again.

**Comment by David-Desmaisons** [comment]
Thanks.
Using props displaylogo="false" should work.

**Comment by Kyxsune** [comment]
Sorry for the lapse in reply, got a little busy. Thanks a bunch, it worked great.
