### ISSUE TITLE
layout prop is ignored

### ISSUE THREAD

**Issue by nboughton** [David-Desmaisons/vue-plotly#8]
I'm trying to create a stacked bar chart but find that the layout prop is being ignored. My .vue file can be seen [here](https://github.com/nboughton/lotto/blob/master/frontend/src/pages/Index.vue)

The relevant line invokes plotly with:

```
<plotly :data="qData.freqDist" :layout="layout.freq" />
```

The relevant data is defined as:

```
 data() {
    return {
      ...
      qData: {},
      layout: {
        freq: {
          title: "Draw Frequency",
          barmode: "stack"
        }
      },
     ...
  }
```
The qData prop is filled via ajax request at page load and after a form action is submitted, might this cause an issue?

**Comment by ped59430** [comment]
The `freqDist` attribute is not reactive if not declared in data.

You can use `this.$set(qData, 'freqDist', yourAjaxReceivedValues)` to make it reactive.

[See this docs](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats)

**Comment by David-Desmaisons** [comment]
@nboughton any news on this?

**Comment by nboughton** [comment]
I've tried adding freqDist as part of the template data:
```
data() {
    return {
    ...
      qData: {
        timeSeries: {},
        freqDist: {}
      },
      layout: {
        freq: {
          title: "Draw Frequency",
          barmode: "stack"
        }
      },
...
}
```

And using set to ensure the data is reactive:
``` 
onSubmit() {
      this.$axios
        .post("/query", this.params)
        .then(res => {
          this.$set(this.qData, "freqDist", res.data.freqDist);
          this.$set(this.qData, "timeSeries", res.data.timeSeries);
          this.$set(this.qData, "mainTable", res.data.mainTable);
        })
        .catch(err => alert(err));
    },
```

However the chart still does not display as stacked bar data.

**Comment by David-Desmaisons** [comment]
Could you create a jsfiddle?

**Comment by nboughton** [comment]
I'm attempting to but I'm not sure how to load vue-plotly on there. I've never used jsfiddle before and the server backend that I send ajax requests to is not deployed publicly. I usually just bake it into a docker image for testing and running.

**Comment by ped59430** [comment]
You can use unpkg https://unpkg.com/ to upload your npm packages in jsfiddle.

For the backend, maybe you can just copy and hardcode a subset of the data, and trigger the `onSubmit()` from a button?

**Comment by nboughton** [comment]
https://jsfiddle.net/hybacw74/1/

I still can't get it to run vue-plotly

**Comment by jomarahi** [comment]
Try this:
`<plotly ref="plot" :data="qData.freqDist" :layout="layout.freq" />`

and add a watch on your layout.freq and qData.freqDist:
```
watch: {
    'qData.freqDist': {
      async handler (val) {
        await this.$nextTick()
        this.$refs.plot.schedule({ replot: false })
      },
      deep: true
    },
    'layout.freq': {
      async handler (val) {
        this.$refs.plot.innerLayout = val
        await this.$nextTick()
        this.$refs.plot.schedule({ replot: false })
      },
      deep: true
    }
  }
```

**Comment by nboughton** [comment]
This works perfectly.

Thank you very much!

**Comment by ped59430** [comment]
Worked also on my barplot ! Thanks !!
